#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting headd daemon"
    [ ! -f /var/run/headd.pid ] && /usr/bin/headd &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon headd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping headd daemon"
    [ -f /var/run/headd.pid ] && kill `cat /var/run/headd.pid`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon headd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
